---
version: '3.7'
services:
  ## Postgres Docker Compose Config
  postgres:
    container_name: postgres-db
    image: postgres:14.2-alpine
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command: -p 5431
    restart: always

  postgres-payment:
    container_name: postgres-payment
    image: postgres:14.2-alpine

    environment:
     POSTGRES_DB: payment
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     PGDATA: /data/postgres
    volumes:
     - ./postgres-payment:/data/postgres
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    restart: always


  ## Eureka Server
  discovery-server:
    image: microservices-tutorial/service-registry:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  api-gateway:
    image: microservices-tutorial/cloud-gateway:latest
    container_name: cloud-gateway
    ports:
      - "9093:9093"
    expose:
      - "9093"
    command: -p 9093 HOST=0.0.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - discovery-server


  redis:
    image: redis
    container_name: redis
    restart: always


  ## Order-Service Docker Compose Config
  order-service:
    container_name: order-service
    image: microservices-tutorial/rdsexample:latest
    expose:
      - "9091"
    ports:
      - "9091:9091"
    command: -p 9091 HOST=0.0.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5431/order
    depends_on:
      - redis
      - postgres
      - payment-service
      - discovery-server
      - api-gateway

  ## Payment-Service Docker Compose Config
  payment-service:
    container_name: payment-service
    image: microservices-tutorial/payment:latest
    expose:
      - "9094"
    ports:
      - "9094:9094"
    command: -p 9094 HOST=0.0.0.0
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5433/payment
    depends_on:
      - postgres-payment
      - discovery-server
      - api-gateway


  ## Prometheus
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - payment-service
      - order-service

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password


